# Prerequisites {#prereqs}

## Platform Support {#plat-support}

Plugins developed with the SDK require the RStudio Launcher to work. The SDK is currently compatible with the version of the RStudio Launcher that is shipped with Rstudio Workbench v1.4. As such, the SDK will be supported on all of the platforms supported by RStudio Workbench v1.4, which can be found on the [Requirements for RStudio Workbench page](https://docs.rstudio.com/rsp/requirements/).

## Build Dependencies {#builddep}

To get started developing a Plugin using the SDK, it is necessary to install the development tools and dependencies required for building and running Plugins.

The SDK provides utilities for installing many of the required libraries, however these scripts require super user access and install packages globally, so they should be used with discretion. Before running the `dependencies/install-dependencies.sh` script, review it carefully to ensure that the default installation locations will be acceptable. Otherwise, it is possible to install the dependencies manually.

The SDK requires the following tools and libraries:

  Name     Minimum Version          Reference
--------  -----------------  -----------------------
gcc/g++   4.8                https://gcc.gnu.org/
cmake     3.15.5             https://cmake.org/
Boost     1.70.0             https://www.boost.org/


## RStudio Workbench {#rsp}

This version of the RStudio Launcher Plugin SDK is compatible with RStudio Workbench version 1.4, or greater. To properly test the integration between a Launcher Plugin and RStudio Workbench, an RStudio Workbench license, with the launcher feature enabled, is required. To acquire a license, please contact sales@rstudio.com.

## Job Scheduling System {#jss}

Each Plugin is intended to interface with a single job scheduling system. In order to test the Plugin implementation, access to a test environment with the desired job scheduling system will be required.
