FROM ubuntu:bionic

COPY dependencies/install-dependencies.sh /tmp/
RUN /tmp/install-dependencies.sh --core

COPY tools/*.sh /tmp/

ARG JENKINS_GID=999
ARG JENKINS_UID=999
RUN groupadd -g $JENKINS_GID jenkins && \
    useradd -m -d /var/lib/jenkins -u $JENKINS_UID -g jenkins jenkins && \
    echo "jenkins ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers