@startuml

[-> Main : launch
activate Main

create Logger
Main -> Logger : new
Main -> Logger : add syslog destination
Main -> Logger : add stderr destination

create Options
Main -> Options : new
Main -> Options ++ : read options
alt success
Main <-- Options -- : success
else error
Main X-- Options -- : error
end

Main -> Logger : remove stderr destination
Main -> Logger : set log level from options

create StdIOFrameworkCommunicator
Main -> StdIOFrameworkCommunicator : new

Main -> Main ++ : createLauncherPluginApi
create PluginApi
Main -> PluginApi ++ : new

PluginApi -> PluginApi ++ : create job source
create JobSource
PluginApi -> JobSource : new
deactivate PluginApi

create JobStatusNotifier
PluginApi -> JobStatusNotifier : new

create JobPruner
PluginApi -> JobPruner ++ : new
JobPruner -> JobStatusNotifier : subscribe
PluginApi <-- JobPruner --

create JobStatusWatcher
PluginApi -> JobStatusWatcher : new

Main <-- PluginApi -- : success
deactivate Main

Main -> Main : register signal handlers

Main -> PluginApi  ++ : initialize
activate Main
StdIOFrameworkCommunicator <- PluginApi ++ : register request handlers
alt success
StdIOFrameworkCommunicator --> PluginApi : success
else error
StdIOFrameworkCommunicator --> PluginApi -- :error
Main X<-- PluginApi : error
end

PluginApi -> JobSource ++ : initialize
create UserProfiles
JobSource -> UserProfiles : new
JobSource -> UserProfiles ++ : read options
alt success
JobSource <-- UserProfiles : success
alt success
PluginApi <-- JobSource : success
else error
PluginApi <-- JobSource : error
Main X<-- PluginApi : error
end
else error
JobSource <-- UserProfiles --: error
PluginApi <-- JobSource --: error
Main X<-- PluginApi : error
end

PluginApi -> JobSource ++ : get all jobs
PluginApi <-- JobSource -- : job list

PluginApi -> JobStatusWatcher ++ : start
Main <-- PluginApi -- : success

deactivate Main

Main -> StdIOFrameworkCommunicator ++ : start

Main -> Main ++ : wait for signal

@enduml
