
FROM ubuntu:bionic

RUN apt-get update && \
    export DEBIAN_FRONTEND=noninteractive && \
    apt-get install -y \
    build-essential \
    clang \
    cmake \
    curl \
    docker.io \
    expect \
    fakeroot \
    gdebi-core \
    git \
    gnupg1 \
    iproute2 \
    libacl1-dev \
    libattr1-dev \
    libbz2-dev \
    libcap-dev \
    libcurl4-openssl-dev \
    libegl1-mesa \
    libfuse2 \
    libgl1-mesa-dev \
    libglib2.0-dev \
    libgtk-3-0 \
    libnss3 \
    libssl-dev \
    libuser1-dev \
    libxml2-dev \
    libxslt1-dev \
    locales \
    lsof \
    ninja-build \
    p7zip-full \
    pkg-config \
    python \
    software-properties-common \
    sudo \
    unzip \
    uuid \
    uuid-dev \
    valgrind \
    vim \
    wget \
    xvfb \
    zlib1g-dev
EXPOSE 8080
